<div id="post-editor">
	<div id="editor-toolbar">
		<div>
			<button id="p" type="button">P</button>
			<button id="h1" type="button">H1</button>
			<button id="h2" type="button">H2</button>
			<button id="h3" type="button">H3</button>
		</div>
		<div>
			<button id="bold" type="button" name="button">Bold</button>
			<button id="italic" type="button">Italic</button>
			<button id="underline" type="button">Underline</button>
			<button id="strike" type="button">Strike</button>
		</div>
		<div>
			<button id="align-left">Left</button>
			<button id="align-center">Center</button>
			<button id="align-right">Right</button>
		</div>
		<div>
			<button id="ol">OL</button>
			<button id="ul">UL</button>
		</div>
		<div>
			<button id="link">Link</button>
		</div>
		
	</div>
	<div id="editor-body" contenteditable="true" autocomplete="off" spellcheck="false"><p>Good words,</p><p>power to the world.</p></div>
</div>
