<div id="post-editor">
	<div id="editor-toolbar">
		<div>
			<button id="p" type="button">P</button>
			<button id="h1" type="button">H1</button>
			<button id="h2" type="button">H2</button>
			<button id="h3" type="button">H3</button>
		</div>
		<div>
			<button id="bold" type="button" name="button">Bold</button>
			<button id="italic" type="button">Italics</button>
			<button id="underline" type="button">Underline</button>
			<button id="strike" type="button">Strikethrough</button>
		</div>
		<div>
			<button id="align-left">Left</button>
			<button id="align-center">Center</button>
			<button id="align-right">Right</button>
		</div>
		<div>
			<button id="ol">목록</button>
			<button id="link">링크</button>
			<!-- <button id="ul">순서가 없는 목록</button> -->
		</div>
		<div>
			
		</div>
		
	</div>
	<div id="editor-body" contenteditable="true" autocomplete="off" spellcheck="false"><p>1</p><p>2</p><p>3</p><p>4</p><p>5</p><p>6</p><p>7</p></div>
</div>
