<div id="post-editor">
	<div id="editor-toolbar">
		<div>
			<button id="p" type="button">본문</button>
			<button id="h1" type="button">제목1</button>
			<button id="h2" type="button">제목2</button>
			<button id="h3" type="button">제목3</button>
		</div>
		<div>
			<button id="bold" type="button" name="button">Bold</button>
			<button id="italic" type="button">기울임</button>
			<button id="underline" type="button">밑줄</button>
			<button id="strike" type="button">취소선</button>
		</div>
		<div>
			<button id="align-left">왼쪽정렬</button>
			<button id="align-center">가운데정렬</button>
			<button id="align-right">오른쪽정렬</button>
		</div>
		<div>
			<button id="ol">목룍</button>
			<button id="link">링크</button>
			<!-- <button id="ul">순서가 없는 목록</button> -->
		</div>
		<div>
			
		</div>
		
	</div>
	<div id="editor-body" contenteditable="true" autocomplete="off" spellcheck="false"><p>Hello</p><p>World</p></div>
</div>
