<div id="post-editor">
	<div id="editor-toolbar">
		<div>
			<button id="p" type="button">P</button>
			<button id="h1" type="button">H1</button>
			<button id="h2" type="button">H2</button>
			<button id="h3" type="button">H3</button>
		</div>
		<div>
			<button id="bold" type="button" name="button">Bold</button>
			<button id="italic" type="button">Italics</button>
			<button id="underline" type="button">Underline</button>
			<button id="strike" type="button">Strikethrough</button>
		</div>
		<div>
			<button id="align-left">Left</button>
			<button id="align-center">Center</button>
			<button id="align-right">Right</button>
		</div>
		<div>
			<button id="ol">List</button>
			<button id="link">Link</button>
			<button id="blockquote">Blockquote</button>
			<!-- <button id="ul">순서가 없는 목록</button> -->
		</div>
		<div>
			<button id="log-range">Log Range</button>
		</div>
		
	</div>
	<div id="editor-body" contenteditable="true" autocomplete="off" spellcheck="false"><p>앙</p><p>기모띠</p><p>앙</p><p>깃머지</p><p>앙</p><p>팡</p><blockquote>Truth is ever to be found in simplicity, and not in the multiplicity and confusion of things.</blockquote><blockquote>Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world.</blockquote></div>
</div>
