<?php
/**
* Table for post.
*
* @author 		H.Chihoon
* @copyright 	2018 DesignAndDevelop
*/

$sql = "CREATE TABLE post (
	id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	user_id INT(11) UNSIGNED NOT NULL,
	title JSON NOT NULL,
	contents JSON NOT NULL,
	is_premium BOOLEAN NOT NULL,
	is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
	view_cnt INT(11) UNSIGNED NOT NULL DEFAULT 0,
	share_cnt INT(11) UNSIGNED NOT NULL DEFAULT 0,
	publication_dt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	last_modified_dt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	series_id INT(11) UNSIGNED,
	thumbnail VARCHAR(512),
	subtitle JSON,
	CONSTRAINT FK__user__post FOREIGN KEY (user_id)
	REFERENCES user (id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK__series__post FOREIGN KEY (series_id)
	REFERENCES series (id) ON DELETE SET NULL ON UPDATE CASCADE

) ENGINE=InnoDB DEFAULT CHARSET=utf8";
