<main id="profile-main">

	<div id="info">
		<div class="profile-image">
			<img src="/assets/images/profile/user-profile-default.svg" alt="">
		</div>
		<h1 class="name">이름 없음</h1>
		<p class="manifesto">지나가는 행인입니다.</p>
	</div>

	<div id="history">
		<ol class="menu">
			<li class="menu-item post selected">포스트</li>
			<li class="menu-item series">시리즈</li>
			<li class="menu-item like">좋아요</li>
			<li class="menu-item comment">코멘트</li>
		</ol>
		<div class="board">
			<div class=""></div>
			<div></div>
			<div></div>
			<div></div>
		</div>
	</div>

</main>