<main id="profile-main">

	<div id="info">
		<div class="profile-image">
			<img src="/assets/images/profile/user-profile-default.svg" alt="">
		</div>
		<h1 class="name">이름 없음</h1>
		<p class="manifesto">지나가는 행인입니다.</p>
	</div>

	<div id="history">
		<ol class="menu">
			<li class="menu-item post selected">포스트</li>
			<li class="menu-item series">시리즈</li>
			<li class="menu-item like">좋아요</li>
			<li class="menu-item comment">코멘트</li>
		</ol>
		<div class="board">
			<div class="board-container board-post selected">
				<h1 class="board-title">포스트</h1>
				<div class="board-item post">
					<h2 class="post-title">장어덮밥을 먹을 수 없게 된다면?</h2>
				</div>
				<div class="board-item post">
					<h2 class="post-title">여행하며 현금관리를 잘 하는법</h2>
				</div>
				<div class="board-item post"></div>
			</div>
			<div class="board-container board-series">
				<h1 class="board-title">시리즈</h1>
			</div>
			<div class="board-container board-like">
				<h1 class="board-title">좋아요</h1>
			</div>
			<div class="board-container board-comment">
				<h1 class="board-title">코멘트</h1>
			</div>
		</div>
	</div>

</main>