<div id="post-editor">
	<div id="editor-toolbar">
		<div>
			<button id="p" type="button">P</button>
			<button id="h1" type="button">H1</button>
			<button id="h2" type="button">H2</button>
			<button id="h3" type="button">H3</button>
		</div>
		<div>
			<button id="bold" type="button" name="button">Bold</button>
			<button id="italic" type="button">Italics</button>
			<button id="underline" type="button">Underline</button>
			<button id="strike" type="button">Strikethrough</button>
		</div>
		<div>
			<button id="align-left">Left</button>
			<button id="align-center">Center</button>
			<button id="align-right">Right</button>
		</div>
		<div>
			<button id="ol">List</button>
			<button id="link">Link</button>
			<button id="blockquote">Blockquote</button>
			<button id="ul">순서가 없는 목록</button>
		</div>
		<div>
			<button id="log-range">Log Range</button>
			<button id="nodes-in-selection">Nodes In Sel</button>
			<button id="separate">Separate</button>
			<button id="split-text">SplitText</button>
		</div>
		<div>
			<button id="get-sel-pos">Get Sel Pos</button>
			<button id="get-sel-pos-par">Get Sel Pos Par</button>
		</div>
		
	</div>
	<div id="caret"></div>
	<aside id="poptool">
		<button id="pt-bold" type="button" name="button"><b>B</b></button>
		<button id="pt-italic" type="button"><i>I</i></button>
		<button id="pt-underline" type="button"><u>U</u></button>
		<button id="pt-strike" type="button"><strike>S</strike></button>
	</aside>
	<div id="editor-body" contenteditable="true" autocomplete="off" spellcheck="false"><h2><b>김치찌개를 맛있게 끓이는 법</b></h2><ul><li>맛있는 김치를 산다.</li><li>맛있는 돼지고기를 산다.</li><li>김치와 돼지고기와 물을 넣고 끓인다.</li></ul></div>
</div>
