<!DOCTYPE html>
<html>

	<head>

		<?php
		// Meta tags included globally
		$this->basis("head_meta", "/global-inclusion/global-meta.php");
		?>

		<title><?php $this->embrace("title"); ?></title>

		<?php
		// CSS' included globally
		$this->basis("html_css", "/global-inclusion/global-css.php");

		// CSS' included manually
		$this->optional("css");

		?>

	</head>

	<body>

		<?php
		$this->basis("render_globalnav", "/global-inclusion/globalnav/globalnav.php");
		?>

		<!-- Main tag -->
		<?php
		$this->embrace("main");
		?>

		<?php
		// Javascript files included globally
		$this->basis("html_script", "/global-inclusion/global-script.php");

		// Javascript files included manually
		$this->optional("script");
		?>

	</body>

</html>
