<!DOCTYPE html>
<html>

	<head>

		<?php
		// Meta tags included globally
		$this->basis("head_meta", "/global-inclusion/global-meta.php");
		?>

		<title><?php $this->embrace("title"); ?></title>

		<?php
		// CSS' included globally
		$this->basis("html_css", "/global-inclusion/global-css.php");

		// CSS' included manually
		$this->optional("css");

		?>

	</head>

	<body>

		<?php
		$this->basis("render_globalnav", "/src/template/globalnav.php");
		?>

		<!-- Main tag -->
		<?php
		$this->embrace("main");
		?>

		<?php
		$this->basis("render_globalfooter", "/src/template/globalfooter.phtml");
		?>

		<?php
		// Javascript files included globally
		// $this->basis("html_script", "/global-inclusion/global-script.php");
		
		$this->basis('GSAP', '<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/2.0.1/TweenMax.min.js"></script>');
		$this->basis('globalscript', '<script src="/global-inclusion/js/globalscript.js"></script>');
		$this->basis('globalnav_script', '<script src="/global-inclusion/globalnav/js/view/gn-view.js"></script>');

		// Javascript files included manually
		$this->optional("script");
		?>

	</body>

</html>
