<main id="register-main">
	<div class="introduce-header">
		<img class="header-icon" src="/assets/images/writing.svg" alt="">
		<h1>좋은 글, 세상을 바꾸는 힘.</h1>
		<!-- <h1>Where words matter.</h1> -->
		<p>지금 가입하여 한 달 동안 무료로<br>모든 서비스를 이용해 보세요.</p>
		<!-- <p>Register now and<br>experience a month for free.</p> -->
	</div>
	<div class="provider">
		<div class="input-wrapper">
			<input class="username input-basic" type="text" autocomplete="off" spellcheck="false">
			<span class="placeholder">아이디</span>
		</div>
		<div class="input-wrapper">
			<input class="email input-basic" type="email" autocomplete="off" spellcheck="false">
			<span class="placeholder">이메일 주소</span>
		</div>
		<div class="input-wrapper">
			<input class="password input-basic" type="password" autocomplete="off" spellcheck="false">
			<span class="placeholder">암호</span>
		</div>
		<button class="btn-violet">시작하기</button>
	</div>
</main>
