<main id="register-main">
	<div class="introduce-header">
		<img class="header-icon" src="/src/images/writing.svg" alt="">
		<h1>좋은 글, 세상을 바꾸는 힘.</h1>
		<!-- <h1>Where words matter.</h1> -->
		<p>지금 가입하고 한 달 동안<br>무료로 이용해 보세요!</p>
		<!-- <p>Register now and<br>experience a month for free.</p> -->
	</div>
	<div class="provider">
		<div class="input-wrapper">
			<label class="placeholder">이메일 주소</label>
			<input class="email input-basic reg-input" type="email" autocomplete="off" spellcheck="false">
		</div>
		<div class="input-wrapper">
			<label class="placeholder">이름</label>
			<input class="username input-basic reg-input" type="text" autocomplete="off" spellcheck="false">
		</div>
		<div class="input-wrapper">
			<label class="placeholder">암호</label>
			<input class="password input-basic reg-input" type="password" autocomplete="off" spellcheck="false">
		</div>
		<button class="btn-violet">시작하기</button>
	</div>
</main>
